### ISSUE TITLE
offtopic: CCRs and lab results

### ISSUE THREAD

**Issue by mrose17** [giladbu/CCRBinder#1]
sorry for the noise!

would it be possible to get a pointer to how one encodes lab results via CCR? neither LabCorp nor Quest Diagnostics have a download "CCR" (or "CCD") button, but only a "PDF" button.

fine, i can run http://tabula.technology/ as well as anyone else and clean up the output. and i can write a transformation program ... if i know what the format/dictionary is... would you be able to help?

many thanks!

/mtr

**Comment by giladbu** [comment]
Not sure I can help. first this code is 6 years old, second I moved away from working on health care records around that time, so I'm not sure what is the state of art this days.

last this library, can help with generating CCR rather than digesting one. to use, you create implementation classes for the interfaces in here: https://github.com/giladbu/CCRBinder/tree/master/src/main/java/com/keas/ccr
and then pass them to CCRBuilder to generate a CCR.

**Comment by mrose17** [comment]
thank you very much... in truth, i realize that while the repo might not be current, as a contributor, you know a lot more than i do.

best,

/mtr
